### ISSUE TITLE
podwójna zmiana koloru

### ISSUE THREAD

**Issue by ravkr** [artur9010/Phoenix#3]
pojedyncze kliknięcie "change color" powoduje że kolor na chacie jest 2 razy zmieniany (oczywiście oba razy na taki sam)
![zrzut ekranu z 2016-08-01 02 23 46](https://cloud.githubusercontent.com/assets/3875202/17280395/3e65feca-578f-11e6-9ada-e1f1a6b8febf.png)

**Comment by ravkr** [comment]
czyli to nie zostanie naprawione... :/

**Comment by artur9010** [comment]
Nie zauważyłem tego u siebie, ani nikt inny mi tego nie zgłaszał.

**Comment by artur9010** [comment]
Tyle co wczoraj było ok, tak dzisiaj mi potrójnie zmienia kolor, więc otwieram.
Wydaje mi się że to problem po stronie facebooka.

**Comment by artur9010** [comment]
No i do tego API informuje mnie że nie jestem zalogowany, a mimo to zmieniam kolor...

ERR! Error in changeThreadColor { error: 'Not logged in.' }

**Comment by wvffle** [comment]
As far as I know this might be due to #5

**Comment by artur9010** [comment]
Fixed
![zrzut ekranu 2016-08-29 o 19 54 27](https://cloud.githubusercontent.com/assets/4835677/18061272/71b06bd6-6e22-11e6-979c-891120ba21ed.png)

Thanks @wvffle

**Comment by wvffle** [comment]
No problem. Just buy me a pizza.

**Comment by wvffle** [comment]
Or waffles. Yup buy me some waffles. That's better idea.

**Comment by artur9010** [comment]
Meh...
